### ISSUE TITLE
Fix electrode

### ISSUE THREAD

**Issue by vladislavivanistsev** [conda-forge/conda-feedstock#227] opened 2023-11-24 01:08 UTC
### Comment:

Could you please add fix electrode by adding the following?

    -D PKG_ELECTRODE=yes \
    -D PKG_KSPACE=yes \
    -D USE_INTERNAL_LINALG=ON \

**Comment by jakirkham** [comment] 2023-12-01 21:54
Could you please add more context? Am not sure what this is referring to

**Comment by mbargull** [comment] 2023-12-05 20:02
Whatever this is supposed to request, this is definitely out of scope here.

**Closed by mbargull** 2023-12-05 20:02 UTC
Labels: question

**Comment by jakirkham** [comment] 2023-12-05 20:06
I'm guessing it was intended for a different feedstock, but didn't have enough to go on from the report to transfer it to the right place
